import type { Capitulo } from './tipos';
import { validarConsulta, validarEscrita } from '../validacao';
import {
  algumaE,
  camposComoReferencia,
  contagemNoArquivo,
  mesmasFichas,
  numUnicoComando,
  numeroCerto,
  objetivo,
  registrou,
  respostaCompleta,
  semCampo,
  somenteCampos,
  todas,
  umDocumentoSo,
  umaFichaNovaSoCom,
} from '../objetivos';
import { IDS } from '../mundo';
import { canonico } from '../../engine/bson';

export const capitulo1: Capitulo = {
  numero: 1,
  titulo: 'Admissão',
  fase: 1,
  abertura: 'Primeiro dia depois da morte. Só o Limbo e o Purgatório estão abertos — o resto do prédio segue interditado desde que a caldeira do Inferno explodiu.',
  missoes: [
    {
      id: '1.1',
      titulo: 'Primeiro expediente',
      assunto: 'Conferência do que sobrou',
      corpo: 'Antes de qualquer coisa, a Diretoria precisa saber o que sobreviveu ao incêndio. Liste todas as fichas da coleção `almas`.',
      objetivos: [objetivo('Listar todos os documentos da coleção almas, com todos os campos.', respostaCompleta)],
      requer: [],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas' }),
      solucaoReferencia: 'db.almas.find()',
      solucoesErradas: [{ codigo: "db.almas.find({ setor: 'Limbo' })", porque: 'filtrou só o Limbo' }],
      dicas: [
        'Todo comando começa com db, seguido do nome da coleção: db.almas',
        'O método find() busca documentos. Sem nada dentro dos parênteses, ele traz todos.',
        'db.almas.find()',
      ],
      recompensa: 2,
      licao: 'find() sem argumentos devolve todos os documentos da coleção.',
    },
    {
      id: '1.2',
      titulo: 'Papelada mínima',
      assunto: 'Relação enxuta para a Correspondência',
      corpo: 'O Setor de Correspondência quer uma relação de todas as almas com apenas o nome e o setor. Eles não sabem ler o `_id` — tire.',
      objetivos: [
        objetivo('Todas as almas.', mesmasFichas),
        objetivo('Somente os campos nome e setor.', somenteCampos(['nome', 'setor'])),
        objetivo('Sem o campo _id.', semCampo('_id')),
      ],
      requer: [],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas' }),
      solucaoReferencia: 'db.almas.find({}, { nome: 1, setor: 1, _id: 0 })',
      solucoesErradas: [
        { codigo: 'db.almas.find({}, { nome: 1, setor: 1 })', porque: 'esqueceu de tirar o _id' },
        { codigo: 'db.almas.find()', porque: 'não projetou os campos' },
      ],
      dicas: [
        'O find aceita um SEGUNDO argumento, a projeção, que escolhe quais campos aparecem. O primeiro argumento (o filtro) pode ser {} para trazer todos.',
        'Na projeção, campo: 1 mostra o campo. O _id aparece sempre, a menos que você escreva _id: 0.',
        'db.almas.find({}, { nome: 1, setor: 1, _id: 0 })',
      ],
      recompensa: 2,
      licao: 'Projeção inclusiva: { campo: 1 } mostra só o que você pediu. O _id só some com _id: 0.',
    },
    {
      id: '1.3',
      titulo: 'Ficha sem gordura',
      assunto: 'Fichas do Purgatório para despacho',
      corpo: 'O Purgatório pediu as fichas completas das suas almas, mas o papel está caro: mande tudo, MENOS `endereco` e `audiencias`.',
      objetivos: [
        objetivo('Todas as almas do setor Purgatório, e só elas.', mesmasFichas),
        objetivo('Todos os campos, exceto endereco e audiencias.', camposComoReferencia),
      ],
      requer: [],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas' }),
      solucaoReferencia: "db.almas.find({ setor: 'Purgatório' }, { endereco: 0, audiencias: 0 })",
      solucoesErradas: [
        { codigo: 'db.almas.find({}, { endereco: 0, audiencias: 0 })', porque: 'não filtrou o Purgatório' },
        { codigo: "db.almas.find({ setor: 'Purgatório' }, { nome: 1, setor: 1 })", porque: 'projeção inclusiva perdeu campos' },
        { codigo: "db.almas.find({ setor: 'Purgatorio' }, { endereco: 0, audiencias: 0 })", porque: 'esqueceu o acento' },
      ],
      dicas: [
        'Primeiro argumento do find: o filtro, no formato { campo: valor }. Segundo: a projeção.',
        'Com campo: 0 a projeção ESCONDE aquele campo e mostra todo o resto.',
        "db.almas.find({ setor: 'Purgatório' }, { endereco: 0, audiencias: 0 })",
      ],
      recompensa: 3,
      licao: 'Projeção exclusiva: { campo: 0 } esconde campos. Não misture 1 e 0 (exceto no _id).',
    },
    {
      id: '1.4',
      titulo: 'A ficha do antecessor',
      assunto: 'Boato no corredor',
      corpo: 'Dizem que apareceu no Limbo uma ficha com o nome do seu antecessor, `Aurélio Vilaverde`. A Diretoria quer essa ficha em mãos — a ficha em si, não uma lista.',
      objetivos: [
        objetivo('Devolver o documento de Aurélio Vilaverde.', algumaE((d) => canonico(d._id) === canonico(IDS.aurelio))),
        objetivo('Um documento só (não uma lista).', umDocumentoSo),
      ],
      requer: ['leitura-rapida'],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas' }),
      solucaoReferencia: "db.almas.findOne({ nome: 'Aurélio Vilaverde' })",
      solucoesErradas: [
        { codigo: "db.almas.find({ nome: 'Aurélio Vilaverde' })", porque: 'devolveu uma lista' },
        { codigo: "db.almas.findOne({ nome: 'Iracema Vilaverde' })", porque: 'pegou a ficha errada' },
      ],
      dicas: [
        'Existe um método que devolve um único documento em vez de uma lista. Ele fica na Árvore de Credenciamento.',
        'findOne recebe o mesmo filtro que o find, mas devolve só o primeiro documento que bate.',
        "db.almas.findOne({ nome: 'Aurélio Vilaverde' })",
      ],
      recompensa: 3,
      licao: 'findOne devolve o documento; find devolve um cursor (uma lista), mesmo que só uma ficha bata.',
    },
    {
      id: '1.5',
      titulo: 'Censo do Purgatório',
      assunto: 'Pedido do Setor de Estatística',
      corpo: 'Quantas almas estão no Purgatório? O Setor de Estatística não aceita lista: quer um número.',
      objetivos: [objetivo('Devolver a quantidade (um número) de almas do setor Purgatório.', numeroCerto)],
      requer: ['recenseamento'],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas' }),
      solucaoReferencia: "db.almas.countDocuments({ setor: 'Purgatório' })",
      solucoesErradas: [
        { codigo: 'db.almas.countDocuments({})', porque: 'contou todas as almas' },
        { codigo: "db.almas.find({ setor: 'Purgatório' })", porque: 'devolveu a lista em vez do número' },
      ],
      dicas: [
        'Contar é outra credencial. Procure na Árvore de Credenciamento.',
        'countDocuments(filtro) devolve quantos documentos batem com o filtro.',
        "db.almas.countDocuments({ setor: 'Purgatório' })",
      ],
      recompensa: 3,
      licao: 'countDocuments(filtro) conta sem trazer os documentos.',
    },
    {
      id: '1.6',
      titulo: 'Ficha de entrada',
      assunto: 'Alma recém-chegada',
      corpo: 'Uma alma acabou de chegar ao balcão. Registre a ficha com exatamente estes dados — nem mais, nem menos.',
      objetivos: [
        objetivo("protocolo: 'A-1953-0101'", registrou({ protocolo: 'A-1953-0101' })),
        objetivo("nome: 'Gaspar Mendonça'", registrou({ nome: 'Gaspar Mendonça' })),
        objetivo("setor: 'Limbo'", registrou({ setor: 'Limbo' })),
        objetivo("pendencia: 'Relógio não devolvido'", registrou({ pendencia: 'Relógio não devolvido' })),
        objetivo('Uma ficha só, sem nenhum campo além desses.', umaFichaNovaSoCom(['protocolo', 'nome', 'setor', 'pendencia'])),
      ],
      requer: ['protocolo-de-entrada'],
      tipo: 'escrita',
      validar: validarEscrita({ colecao: 'almas' }),
      solucaoReferencia: "db.almas.insertOne({ protocolo: 'A-1953-0101', nome: 'Gaspar Mendonça', setor: 'Limbo', pendencia: 'Relógio não devolvido' })",
      solucoesErradas: [
        { codigo: "db.almas.insertOne({ nome: 'Gaspar Mendonça', setor: 'Limbo' })", porque: 'faltaram campos' },
        { codigo: "db.almas.insertOne({ protocolo: 'A-1953-0101', nome: 'Gaspar Mendonça', setor: 'limbo', pendencia: 'Relógio não devolvido' })", porque: 'setor em minúsculas' },
      ],
      dicas: [
        'Gravar um documento é a credencial Protocolo de Entrada.',
        'insertOne recebe o documento entre chaves: { campo: valor, campo: valor }. Textos vão entre aspas.',
        "db.almas.insertOne({ protocolo: 'A-1953-0101', nome: 'Gaspar Mendonça', setor: 'Limbo', pendencia: 'Relógio não devolvido' })",
      ],
      recompensa: 3,
      licao: 'insertOne grava um documento. Sem _id, o MongoDB cria um ObjectId sozinho.',
    },
    {
      id: '1.7',
      titulo: 'Lote da madrugada',
      assunto: 'Três chegadas de uma vez',
      corpo: 'Chegaram três almas durante a madrugada. A Diretoria quer as três registradas num ÚNICO despacho — comando por comando é desperdício de carimbo.',
      objetivos: [
        objetivo("{ nome: 'Celeste Amaral', setor: 'Purgatório' }", registrou({ nome: 'Celeste Amaral', setor: 'Purgatório' })),
        objetivo("{ nome: 'Honório Rangel', setor: 'Limbo' }", registrou({ nome: 'Honório Rangel', setor: 'Limbo' })),
        objetivo("{ nome: 'Quitéria Xavier', setor: 'Limbo' }", registrou({ nome: 'Quitéria Xavier', setor: 'Limbo' })),
        objetivo('Tudo num único comando insertMany.', numUnicoComando('insertMany')),
      ],
      requer: ['despacho-em-lote'],
      tipo: 'escrita',
      validar: validarEscrita({
        colecao: 'almas',
        exigirMetodo: { metodo: 'insertMany', mensagem: 'O arquivo ficou certo, mas a Diretoria pediu UM despacho em lote: use insertMany.' },
      }),
      solucaoReferencia: "db.almas.insertMany([{ nome: 'Celeste Amaral', setor: 'Purgatório' }, { nome: 'Honório Rangel', setor: 'Limbo' }, { nome: 'Quitéria Xavier', setor: 'Limbo' }])",
      solucoesErradas: [
        {
          codigo: "db.almas.insertOne({ nome: 'Celeste Amaral', setor: 'Purgatório' }); db.almas.insertOne({ nome: 'Honório Rangel', setor: 'Limbo' }); db.almas.insertOne({ nome: 'Quitéria Xavier', setor: 'Limbo' })",
          porque: 'três insertOne em vez de um lote',
        },
        { codigo: "db.almas.insertMany([{ nome: 'Celeste Amaral', setor: 'Purgatório' }, { nome: 'Honório Rangel', setor: 'Limbo' }])", porque: 'esqueceu uma alma' },
      ],
      dicas: [
        'Existe uma credencial para gravar vários documentos de uma vez.',
        'insertMany recebe uma LISTA (entre colchetes) de documentos: [ {...}, {...} ].',
        "db.almas.insertMany([{ nome: 'Celeste Amaral', setor: 'Purgatório' }, { nome: 'Honório Rangel', setor: 'Limbo' }, { nome: 'Quitéria Xavier', setor: 'Limbo' }])",
      ],
      recompensa: 4,
      licao: 'insertMany([ ... ]) grava uma lista inteira num só comando.',
    },
    {
      id: '1.8',
      titulo: 'O lote reenviado',
      assunto: 'Correspondência mandou de novo',
      corpo: 'A Correspondência reenviou um lote de cinco fichas. Uma delas já está no arquivo (mesmo `_id`) e o servidor vai reclamar. As outras quatro precisam entrar mesmo assim. O lote já está no seu terminal, na variável `lote`.',
      objetivos: [
        objetivo(
          'Registrar as quatro fichas novas do lote.',
          todas(...['A-1953-0201', 'A-1953-0203', 'A-1953-0204', 'A-1953-0205'].map((protocolo) => registrou({ protocolo }))),
        ),
        objetivo('A ficha repetida (Odorico Paz) continua uma só.', contagemNoArquivo((d) => d.nome === 'Odorico Paz', 1)),
      ],
      anexo: {
        variavel: 'lote',
        codigo: [
          'const lote = [',
          "  { protocolo: 'A-1953-0201', nome: 'Josefina Queiroz', setor: 'Purgatório' },",
          "  { _id: ObjectId('5f1953000000000000000002'), protocolo: 'A-1951-0007', nome: 'Odorico Paz', setor: 'Purgatório' },",
          "  { protocolo: 'A-1953-0203', nome: 'Macário Bittencourt', setor: 'Limbo' },",
          "  { protocolo: 'A-1953-0204', nome: 'Noêmia Pacheco', setor: 'Limbo' },",
          "  { protocolo: 'A-1953-0205', nome: 'Olegário Moura', setor: 'Purgatório' }",
          ']',
        ].join('\n'),
      },
      requer: ['despacho-em-lote'],
      tipo: 'escrita',
      validar: validarEscrita({ colecao: 'almas' }),
      solucaoReferencia: 'db.almas.insertMany(lote, { ordered: false })',
      solucoesErradas: [{ codigo: 'db.almas.insertMany(lote)', porque: 'parou no primeiro erro' }],
      dicas: [
        'Rode db.almas.insertMany(lote) e leia o erro com calma: E11000 quer dizer chave duplicada. Quantas fichas entraram?',
        'Por padrão, o insertMany PARA no primeiro erro. Ele aceita um segundo argumento com opções.',
        'db.almas.insertMany(lote, { ordered: false })',
      ],
      recompensa: 4,
      licao: 'insertMany para no primeiro erro; com { ordered: false } ele grava todos os documentos válidos.',
    },
  ],
};
