import type { Capitulo } from './tipos';
import { validarConsulta } from '../validacao';
import { incluiTodasQue, mesmasFichas, nenhumaDeFora, objetivo, ordenadaPor, todas, todasSao } from '../objetivos';
import { lerCaminho } from '../../engine/bson';

type Doc = Record<string, unknown>;
const anos = (d: Doc) => (typeof d.anos_pendentes === 'number' ? d.anos_pendentes : NaN);

const consulta = validarConsulta({ colecao: 'almas' });

export const capitulo2: Capitulo = {
  numero: 2,
  titulo: 'Triagem',
  fase: 2,
  abertura: 'Acharam caixas chamuscadas no porão, colado às caldeiras do Inferno: 292 fichas foram digitadas às pressas durante a noite. Todos os setores foram reabertos. Ler ficha por ficha deixou de ser opção.',
  missoes: [
    {
      id: '2.1',
      titulo: 'Quem está no Limbo',
      assunto: 'Chamada do Limbo',
      corpo: 'Com o porão digitado, o Limbo lotou. Traga as fichas de todas as almas do setor Limbo.',
      objetivos: [
        objetivo('Somente almas do setor Limbo.', todasSao((d) => d.setor === 'Limbo')),
        objetivo('Nenhuma alma do Limbo ficou de fora.', nenhumaDeFora()),
      ],
      requer: [],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ setor: 'Limbo' })",
      solucoesErradas: [
        { codigo: "db.almas.find({ setor: 'limbo' })", porque: 'minúsculas' },
        { codigo: "db.almas.find({ setor: 'Purgatório' })", porque: 'setor errado' },
      ],
      dicas: ['O filtro é o primeiro argumento do find.', 'Filtro de igualdade: { campo: valor }. Maiúsculas importam.', "db.almas.find({ setor: 'Limbo' })"],
      recompensa: 2,
      licao: 'Filtro de igualdade: { campo: valor }. O valor precisa ser idêntico, inclusive maiúsculas e acentos.',
    },
    {
      id: '2.2',
      titulo: 'Endereço conhecido',
      assunto: 'Visita ao bairro da Lapa',
      corpo: 'Um mensageiro vai à Lapa amanhã. Traga as almas cujo `bairro`, dentro de `endereco`, seja Lapa.',
      objetivos: [
        objetivo('Somente almas com endereco.bairro igual a Lapa.', todasSao((d) => lerCaminho(d, 'endereco.bairro') === 'Lapa')),
        objetivo('Nenhuma alma da Lapa ficou de fora.', nenhumaDeFora()),
      ],
      requer: [],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ 'endereco.bairro': 'Lapa' })",
      solucoesErradas: [{ codigo: "db.almas.find({ endereco: { bairro: 'Lapa' } })", porque: 'comparou o subdocumento inteiro' }],
      dicas: [
        'bairro fica DENTRO do subdocumento endereco.',
        'Para chegar num campo interno, use dot notation entre aspas: "endereco.bairro". Escrever { endereco: { bairro: ... } } exige que o endereço inteiro seja só isso.',
        "db.almas.find({ 'endereco.bairro': 'Lapa' })",
      ],
      recompensa: 3,
      licao: 'Dot notation ("endereco.bairro") consulta campos dentro de subdocumentos.',
    },
    {
      id: '2.3',
      titulo: 'Pendências antigas',
      assunto: 'Casos crônicos',
      corpo: 'A Diretoria quer as almas com MAIS de 60 anos de pendência (`anos_pendentes`). Exatamente 60 não entra.',
      objetivos: [
        objetivo('Somente almas com anos_pendentes maior que 60 (60 não entra).', todasSao((d) => anos(d) > 60)),
        objetivo('Nenhuma com mais de 60 anos ficou de fora.', nenhumaDeFora()),
      ],
      requer: ['regua-de-comparacao'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: 'db.almas.find({ anos_pendentes: { $gt: 60 } })',
      solucoesErradas: [{ codigo: 'db.almas.find({ anos_pendentes: { $gte: 60 } })', porque: 'incluiu o 60' }],
      dicas: ['Comparações são operadores que começam com $.', '{ campo: { $gt: valor } } significa "maior que".', 'db.almas.find({ anos_pendentes: { $gt: 60 } })'],
      recompensa: 3,
      licao: '$gt é "maior que"; $gte é "maior ou igual".',
    },
    {
      id: '2.4',
      titulo: 'A faixa exata',
      assunto: 'Revisão por década',
      corpo: 'O Purgatório vai revisar as almas com pendência entre 10 e 20 anos — incluindo 10 e 20.',
      objetivos: [
        objetivo('Somente almas do setor Purgatório.', todasSao((d) => d.setor === 'Purgatório')),
        objetivo('Somente anos_pendentes de 10 a 20.', todasSao((d) => anos(d) >= 10 && anos(d) <= 20)),
        objetivo('Incluindo quem tem exatamente 10 ou 20 — nenhuma de fora.', nenhumaDeFora()),
      ],
      requer: ['regua-de-comparacao'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ setor: 'Purgatório', anos_pendentes: { $gte: 10, $lte: 20 } })",
      solucoesErradas: [
        { codigo: "db.almas.find({ setor: 'Purgatório', anos_pendentes: { $gt: 10, $lt: 20 } })", porque: 'deixou de fora 10 e 20' },
        { codigo: 'db.almas.find({ anos_pendentes: { $gte: 10, $lte: 20 } })', porque: 'não filtrou o setor' },
      ],
      dicas: [
        'Duas condições no mesmo filtro, separadas por vírgula, precisam ser verdadeiras ao mesmo tempo.',
        'Uma faixa é dois operadores no mesmo campo: { $gte: mínimo, $lte: máximo }.',
        "db.almas.find({ setor: 'Purgatório', anos_pendentes: { $gte: 10, $lte: 20 } })",
      ],
      recompensa: 3,
      licao: 'Vírgula no filtro é E (AND). Faixa inclusiva: { $gte: a, $lte: b }.',
    },
    {
      id: '2.5',
      titulo: 'Tudo, menos o Limbo',
      assunto: 'Almas ativas fora do Limbo',
      corpo: 'Traga as almas ATIVAS (`ativo: true`) de qualquer setor, exceto o Limbo.',
      objetivos: [
        objetivo('Somente almas com ativo: true.', todasSao((d) => d.ativo === true)),
        objetivo('Nenhuma do setor Limbo.', todasSao((d) => d.setor !== 'Limbo')),
        objetivo('Nenhuma que se encaixe ficou de fora.', nenhumaDeFora()),
      ],
      requer: ['regua-de-comparacao'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ setor: { $ne: 'Limbo' }, ativo: true })",
      solucoesErradas: [{ codigo: "db.almas.find({ setor: { $ne: 'Limbo' } })", porque: 'esqueceu o ativo' }],
      dicas: ['"Diferente de" também é um operador de comparação.', '$ne significa not equal. Booleanos não levam aspas: true.', "db.almas.find({ setor: { $ne: 'Limbo' }, ativo: true })"],
      recompensa: 3,
      licao: '$ne é "diferente de". true e false são booleanos, sem aspas.',
    },
    {
      id: '2.6',
      titulo: 'Ou um, ou outro',
      assunto: 'Relatório conjunto',
      corpo: 'A Ante-Sala e o Setor de Casos Crônicos vão dividir um relatório: entram as almas da Ante-Sala OU qualquer alma com mais de 85 anos de pendência.',
      objetivos: [
        objetivo('Todas as almas da Ante-Sala.', incluiTodasQue((d) => d.setor === 'Ante-Sala')),
        objetivo('Todas as almas com mais de 85 anos de pendência, de qualquer setor.', incluiTodasQue((d) => anos(d) > 85)),
        objetivo('Nenhuma outra além dessas.', todasSao((d) => d.setor === 'Ante-Sala' || anos(d) > 85)),
      ],
      requer: ['logica-cartorial'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ $or: [{ setor: 'Ante-Sala' }, { anos_pendentes: { $gt: 85 } }] })",
      solucoesErradas: [{ codigo: "db.almas.find({ setor: 'Ante-Sala', anos_pendentes: { $gt: 85 } })", porque: 'usou E em vez de OU' }],
      dicas: ['Vírgula é E. Para OU você precisa de um operador lógico.', '$or recebe uma LISTA de condições: { $or: [ {...}, {...} ] }.', "db.almas.find({ $or: [{ setor: 'Ante-Sala' }, { anos_pendentes: { $gt: 85 } }] })"],
      recompensa: 3,
      licao: '$or: [ cond1, cond2 ] traz o que satisfaz pelo menos uma condição.',
    },
    {
      id: '2.7',
      titulo: 'Nem um, nem outro',
      assunto: 'Os esquecidos',
      corpo: 'Traga as almas que NÃO estão no Limbo e que também NÃO estão ativas. Nenhuma das duas coisas.',
      objetivos: [
        objetivo('Nenhuma alma do setor Limbo.', todasSao((d) => d.setor !== 'Limbo')),
        objetivo('Nenhuma alma com ativo: true.', todasSao((d) => d.ativo !== true)),
        objetivo('Todas as que sobram, nenhuma de fora.', nenhumaDeFora()),
      ],
      requer: ['logica-cartorial'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ $nor: [{ setor: 'Limbo' }, { ativo: true }] })",
      solucoesErradas: [{ codigo: "db.almas.find({ $or: [{ setor: 'Limbo' }, { ativo: true }] })", porque: 'usou $or' }],
      dicas: ['Existe o contrário do $or.', '$nor: [ cond1, cond2 ] traz o que não satisfaz NENHUMA das condições.', "db.almas.find({ $nor: [{ setor: 'Limbo' }, { ativo: true }] })"],
      recompensa: 3,
      licao: '$nor é "nem isto, nem aquilo".',
    },
    {
      id: '2.8',
      titulo: 'Plantão duplo',
      assunto: 'Escala do fim de semana',
      corpo: 'O plantão cobre almas do Limbo ou do Purgatório que, além disso, tenham mais de 70 anos de pendência ou estejam inativas. São dois "ou" ao mesmo tempo.',
      objetivos: [
        objetivo('Somente almas do Limbo ou do Purgatório…', todasSao((d) => d.setor === 'Limbo' || d.setor === 'Purgatório')),
        objetivo('…que também tenham anos_pendentes > 70 ou ativo: false.', todasSao((d) => anos(d) > 70 || d.ativo === false)),
        objetivo('Nenhuma que se encaixe ficou de fora.', nenhumaDeFora()),
      ],
      requer: ['logica-cartorial'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia:
        "db.almas.find({ $and: [ { $or: [{ setor: 'Limbo' }, { setor: 'Purgatório' }] }, { $or: [{ anos_pendentes: { $gt: 70 } }, { ativo: false }] } ] })",
      solucoesErradas: [
        {
          codigo: "db.almas.find({ $or: [{ setor: 'Limbo' }, { setor: 'Purgatório' }], $or: [{ anos_pendentes: { $gt: 70 } }, { ativo: false }] })",
          porque: 'duas chaves $or no mesmo objeto (a segunda apaga a primeira)',
        },
      ],
      dicas: [
        'Tente escrever dois $or no mesmo objeto e compare o resultado. Num objeto JavaScript, chave repetida sobrescreve a anterior.',
        'Quando o mesmo operador aparece duas vezes, cada um vai num objeto separado dentro de um $and: { $and: [ {...}, {...} ] }.',
        "db.almas.find({ $and: [ { $or: [{ setor: 'Limbo' }, { setor: 'Purgatório' }] }, { $or: [{ anos_pendentes: { $gt: 70 } }, { ativo: false }] } ] })",
      ],
      recompensa: 4,
      licao: 'O $and explícito é necessário quando você repete um operador, como dois $or.',
    },
    {
      id: '2.9',
      titulo: 'Lista fechada',
      assunto: 'Pendências sensíveis',
      corpo: 'Traga as almas com pendência `Dívida de jogo`, `Herança disputada` ou `Segredo de família` — mas que NÃO estejam no Arquivo Morto nem na Correspondência.',
      objetivos: [
        objetivo('Somente pendências da lista.', todasSao((d) => ['Dívida de jogo', 'Herança disputada', 'Segredo de família'].includes(d.pendencia as string))),
        objetivo('Nenhuma do Arquivo Morto ou da Correspondência.', todasSao((d) => d.setor !== 'Arquivo Morto' && d.setor !== 'Correspondência')),
        objetivo('Nenhuma que se encaixe ficou de fora.', nenhumaDeFora()),
      ],
      requer: ['lista-oficial'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia:
        "db.almas.find({ pendencia: { $in: ['Dívida de jogo', 'Herança disputada', 'Segredo de família'] }, setor: { $nin: ['Arquivo Morto', 'Correspondência'] } })",
      solucoesErradas: [{ codigo: "db.almas.find({ pendencia: { $in: ['Dívida de jogo', 'Herança disputada', 'Segredo de família'] } })", porque: 'não excluiu os setores' }],
      dicas: ['Vários valores possíveis para o mesmo campo pedem uma lista.', '$in: [...] = está na lista. $nin: [...] = não está na lista.', "db.almas.find({ pendencia: { $in: ['Dívida de jogo', 'Herança disputada', 'Segredo de família'] }, setor: { $nin: ['Arquivo Morto', 'Correspondência'] } })"],
      recompensa: 3,
      licao: '$in e $nin trocam vários $or/$ne no mesmo campo por uma lista.',
    },
    {
      id: '2.10',
      titulo: 'Fichas rasgadas',
      assunto: 'CEPs perdidos',
      corpo:
        'Os Correios do além devolveram cartas: falta o CEP. Traga TODAS as almas cuja ficha não tem `endereco.cep`. Isso acontece de dois jeitos: fichas que têm o subdocumento `endereco`, mas sem o campo `cep` dentro dele; e fichas rasgadas, sem o `endereco` inteiro (e, portanto, sem CEP também).',
      objetivos: [
        objetivo(
          'As que têm endereco, mas sem cep dentro dele.',
          todas(todasSao((d) => lerCaminho(d, 'endereco.cep') === undefined), incluiTodasQue((d) => 'endereco' in d && lerCaminho(d, 'endereco.cep') === undefined)),
        ),
        objetivo('E também as que não têm endereco nenhum.', incluiTodasQue((d) => !('endereco' in d))),
      ],
      requer: ['pericia-de-fichas'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ 'endereco.cep': { $exists: false } })",
      solucoesErradas: [{ codigo: 'db.almas.find({ endereco: { $exists: false } })', porque: 'só pegou quem não tem endereço' }],
      dicas: ['O que importa aqui é a PRESENÇA do campo, não o valor.', '$exists: false traz documentos sem o campo. Combine com dot notation.', "db.almas.find({ 'endereco.cep': { $exists: false } })"],
      recompensa: 3,
      licao:
        "$exists: false traz quem não tem o campo. Com dot notation ('endereco.cep'), isso inclui os dois casos: subdocumento sem o campo e documento sem o subdocumento.",
    },
    {
      id: '2.11',
      titulo: 'Tipo errado',
      assunto: 'Digitação apressada',
      corpo: 'Alguém digitou `anos_pendentes` como texto ("37" em vez de 37) em várias fichas. Encontre todas.',
      objetivos: [
        objetivo('Somente almas com anos_pendentes gravado como texto (string).', todasSao((d) => typeof d.anos_pendentes === 'string')),
        objetivo('Nenhuma delas ficou de fora.', nenhumaDeFora()),
      ],
      requer: ['pericia-de-fichas'],
      tipo: 'consulta',
      validar: consulta,
      solucaoReferencia: "db.almas.find({ anos_pendentes: { $type: 'string' } })",
      solucoesErradas: [{ codigo: "db.almas.find({ setor: 'Arquivo Morto' })", porque: 'pegou o setor inteiro' }],
      dicas: ['O MongoDB guarda o tipo de cada valor, e dá para filtrar por ele.', "$type: 'string' traz os valores que são texto.", "db.almas.find({ anos_pendentes: { $type: 'string' } })"],
      recompensa: 3,
      licao: '$type filtra pelo tipo BSON. Dado legado costuma ter número gravado como texto.',
    },
    {
      id: '2.12',
      titulo: 'Fila do balcão',
      assunto: 'Atendimento por ordem de chegada',
      corpo: 'O balcão atende as almas do Limbo pela data de falecimento, da mais antiga para a mais recente, 10 por página. Os atendentes já passaram pelas páginas 1 e 2. Entregue a página 3, na ordem.',
      objetivos: [
        objetivo('Somente almas do Limbo.', todasSao((d) => d.setor === 'Limbo')),
        objetivo('Ordenadas por falecimento, da mais antiga para a mais recente.', ordenadaPor('falecimento', 1)),
        objetivo('Exatamente a página 3 (10 fichas por página).', mesmasFichas()),
      ],
      requer: ['fila-organizada'],
      tipo: 'consulta',
      validar: validarConsulta({ colecao: 'almas', ordem: true }),
      solucaoReferencia: "db.almas.find({ setor: 'Limbo' }).sort({ falecimento: 1 }).skip(20).limit(10)",
      solucoesErradas: [
        { codigo: "db.almas.find({ setor: 'Limbo' }).sort({ falecimento: 1 }).skip(30).limit(10)", porque: 'pulou páginas demais' },
        { codigo: "db.almas.find({ setor: 'Limbo' }).sort({ falecimento: -1 }).skip(20).limit(10)", porque: 'ordem invertida' },
      ],
      dicas: ['Três métodos encadeados depois do find: ordenar, pular e limitar.', 'sort({ campo: 1 }) é crescente. A página p pula (p − 1) × 10 fichas.', "db.almas.find({ setor: 'Limbo' }).sort({ falecimento: 1 }).skip(20).limit(10)"],
      recompensa: 4,
      licao: 'Paginação: sort + skip((página − 1) × tamanho) + limit(tamanho).',
    },
  ],
};
